# Copyright (c) 2026, ErpGenEx
# Auto-generated by Global Excellence safe_gap_fixes

import frappe
from frappe import _


def execute(filters=None):
	filters = frappe._dict(filters or {})
	conditions = ["1=1"]
	pass
	where_clause = " AND ".join(conditions)
	data = frappe.db.sql(
		f"""
		SELECT `name`, `agent_name`, `agent_role`, `default_provider`
		FROM `tabAI Agent`
		WHERE {where_clause}
		ORDER BY modified DESC
		LIMIT 500
		""",
		filters,
		as_dict=True,
	)
	columns = [
		{"label": _("Name"), "fieldname": "name", "fieldtype": "Link", "width": 140},
		{"label": _("Agent Name"), "fieldname": "agent_name", "fieldtype": "Data", "width": 180},
		{"label": _("Agent Role"), "fieldname": "agent_role", "fieldtype": "Data", "width": 120},
		{"label": _("Default Provider"), "fieldname": "default_provider", "fieldtype": "Link", "width": 140}
	]
	return columns, data
